/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REQ_H_RPCGEN
#define _REQ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *str_t;

struct t_string {
	str_t data;
};
typedef struct t_string t_string;

struct t_pair {
	str_t authorization;
	str_t data;
};
typedef struct t_pair t_pair;

#define REQ_PROG 0x23451111
#define REQ_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define req_receipt 1
extern  t_string * req_receipt_1(t_string *, CLIENT *);
extern  t_string * req_receipt_1_svc(t_string *, struct svc_req *);
#define req 2
extern  t_string * req_1(t_pair *, CLIENT *);
extern  t_string * req_1_svc(t_pair *, struct svc_req *);
extern int req_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define req_receipt 1
extern  t_string * req_receipt_1();
extern  t_string * req_receipt_1_svc();
#define req 2
extern  t_string * req_1();
extern  t_string * req_1_svc();
extern int req_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str_t (XDR *, str_t*);
extern  bool_t xdr_t_string (XDR *, t_string*);
extern  bool_t xdr_t_pair (XDR *, t_pair*);

#else /* K&R C */
extern bool_t xdr_str_t ();
extern bool_t xdr_t_string ();
extern bool_t xdr_t_pair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REQ_H_RPCGEN */
