/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "req.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

t_string *
req_receipt_1(t_string *argp, CLIENT *clnt)
{
	static t_string clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, req_receipt,
		(xdrproc_t) xdr_t_string, (caddr_t) argp,
		(xdrproc_t) xdr_t_string, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

t_string *
req_1(t_pair *argp, CLIENT *clnt)
{
	static t_string clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, req,
		(xdrproc_t) xdr_t_pair, (caddr_t) argp,
		(xdrproc_t) xdr_t_string, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
