/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "req.h"
#include <unistd.h>

/* prototypes for clightning API */
void cl_pay_invoice(char *);

void
ppc_request(char *host, char *request) {
	CLIENT *clnt;
	t_string  *authorizationLabledinvoice;
	t_string  req_receipt_1_arg;
	t_string  *result_2;
	t_pair  req_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, REQ_PROG, REQ_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	req_receipt_1_arg.data = request;  /* Added argument */
	printf("[1]::RPC: Client requesting server to provide invoice for PPC call\n");
        sleep(3);
	authorizationLabledinvoice = req_receipt_1(&req_receipt_1_arg, clnt);
	printf("[5]::RPC: Client received bolt11_invoice from server\n");
	if (authorizationLabledinvoice == (t_string *) NULL) {
		clnt_perror (clnt, "call failed");
	}
/*	else
	{
		cl_pay_invoice(invoice->data);
	}
	req_1_arg.authorizationLabeldInvoice = invoice->data;  ###MKG Fix THis */
	req_1_arg.data = request;

	printf("[7]::RPC: Client requesting service from server\n");
	result_2 = req_1(&req_1_arg, clnt);
	if (result_2 == (t_string *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("[12]::RPC: Client received result of query: %s\n", result_2->data);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("Client initialting Pay Per Call (PPC) request\n");
	ppc_request (host, "Request_String");     /* Pass new param to PPC request */
	exit (0);
}
